### ISSUE TITLE
v0.2.0 release checklist

### ISSUE THREAD

**Issue by jcheng5** [posit-dev/shiny-vscode#55]
- [x] Sign-off from QA
- [x] Check version number in package.json
- [x] Update CHANGELOG.md
- [x] Ensure CHANGELOG.md version number is correct
- [x] Smoke test
- [x] Create release on GitHub with a vX.Y.Z tag, pasting in the changelog entries
- [x] Add `.vsix` to release artifacts
- [x] Blog/slack if appropriate
- [x] After publish, increment version number
